GerenciaCinema/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from aplicativo.urls import urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urlpatterns))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicativo/urls.py
from django.conf.urls.static import static
from aplicativo.views import index, index_auth, filmes, sessoes, assentos, logar, deslogar, cadastro, administrador, indisponivel
from django.urls import path
from GerenciaCinema import settings

app_name = 'aplicativo'

urlpatterns = [
    path('', index),
    path('indisponivel', indisponivel, name='indisponivel'),
    path('index_auth', index_auth, name='index_auth'),
    path('filmes', filmes, name='filmes'),
    path('sessoes', sessoes, name='sessoes'),
    path('assentos', assentos, name='assentos'),
    path('logar', logar, name='logar'),
    path('deslogar', deslogar, name='deslogar'),
    path('cadastro', cadastro, name='cadastro'),
    path('administrador', administrador, name='administrador'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicativo_usuario/urls.py
"""from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='user_side'

urlpatterns = [
    path('dashboard/', views.UserDashboard.as_view(), name='dashboard'),
    path('booktickets/', views.BookTickets.as_view(), name='booktickets'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('selectseats/<int:pk>', views.BuyTicket.as_view(), name='selectseats'),
    path('history/', views.BookHistory.as_view(), name='bookhistory'),
    path('download/', views.DownloadTicket.as_view(), name='download'),
    path('ticket/<int:pk>', views.Ticket.as_view(), name ='ticket')
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

aplicativo_usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie_name = models.CharField(max_length=50)
    date = models.DateField()
    show = models.IntegerField()
    seats = models.CharField(max_length=50)
    
class BookedSeatsModel(models.Model):
    movie_name = models.CharField(max_length=50)
    date = models.DateField()
    time = models.IntegerField()
    seats = models.CharField(max_length=50)
    number = models.IntegerField(default=0)

aplicativo_usuario/forms.py
"""from django import forms
from . import models
# from mysite.movie.models import SetMovie
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):

    password1 = forms.CharField(
        label = "Senha",
        widget=forms.PasswordInput(attrs={'class':'form-control'})
    )

    password2 = forms.CharField(
    label = "Confirmar Senha",
    widget=forms.PasswordInput(attrs={'class':'form-control'})
    )

    class Meta:
        model = User
        fields = ['username', 'email',]

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            # 'password1':forms.PasswordInput(attrs={'class':'form-control'}),
            # 'password2': forms.PasswordInput(attrs={'class':'form-control'}),
        }

class BookedSeatsForm(forms.Form):
    booked_seats = forms.CharField()

class CheckDateForm(forms.Form):
    date_start = forms.DateField(widget= forms.DateInput(attrs={'name':'date_s'}))
    date_end = forms.DateField(widget = forms.DateInput(attrs={'name':'date_e'}))
    book_date = forms.DateField(widget = forms.DateInput(attrs={'name':'datee'}))
   
    def clean(self):
        all_clean_data = super().clean()
        d_start = all_clean_data['data_start']
        d_end = all_clean_data['date_end']
        datee = all_clean_data['book_date']

        if datee < d_start or datee > d_end:
            raise forms.ValidationError("Wrong date entered")
"""
    

aplicativo_usuario/views.py
"""from django.shortcuts import render, redirect
from . import models
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from . import forms
from django.contrib import messages
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
# from mysite.movie import models as movie_models
from aplicativo.models import MovieMaster, SetMovie
from .models import User
import urllib
from django.urls import reverse
from itertools import chain
from operator import attrgetter

####### User register page#####
def registerPage(request):
    form = forms.CreateUserForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username') 
            return redirect('../login/')
            messages.success(request, 'Account was created'+user)
        else:
            context = {'form': form}
            return render(request, 'aplicativo_usuario/register.html',context)
            
    context = {'form': form}
    return render(request, 'aplicativo_usuario/register.html', context)


##### User Login page#########
def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        print(password)
        user = authenticate(request, username=username, password=password)
        # user.is_superuser
        if user is not None:
            login(request, user)
            # print("hi")
            print("----------------------------")
            print(user.id)
            print("-----------------------------")
            # request.session['user'] = user
            # print(request.session['user'].id)
            # return render(request, 'aplicativo_usuario/user_dashboard.html')
            return redirect('../dashboard/')
            # redirect('dashboard')
            # return redirect(reverse('user_side:dashboard'))
        else:
            print("no")
            messages.info(request, '!!Incorrect credientials!!')

  
    return render(request, 'aplicativo_usuario/login.html')


def userLogout(request):
    logout(request)
    return redirect('../login/')

# Movie seating arrangement page here user will be able to select particular seat number to book it//////////////////////////////////////////////////////
class BookTickets(View):
    form_class = forms.BookedSeatsForm
    initial = {'key': 'value'}
    template_name = "aplicativo_usuario/bookticket.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        dd = '2022-01-01'

        # Sessions for movie seat data //////////////////////////////////////////////////////////

        time_s = request.session['time']
        date_s = request.session['date']  
        movie_name = request.session['moviename']
        time_fld=0
        # ////////////////////////////////////////////////////////////////////////////////

        if time_s == "Manhã":
            time_fld = 1

        elif time_s == "Tarde":
            time_fld = 2
        
        elif time_s == "Noite":
            time_fld = 3

        else:
            time_fld = 4

        print("here")
        print(request.user.id)
        # print(request.session['user'].id)
        new_dict = {val:0 for val in range(60)} 
        
        ###########See if previously any seats are booked for this particular show#############
        if models.BookedSeatsModel.objects.filter(date=date_s, time=time_fld, movie_name = movie_name).exists():
        
            bookseats = models.BookedSeatsModel.objects.get(date=date_s, time=time_fld, movie_name = movie_name) 
            temp = bookseats.seats
            print(temp)
            
            for i in temp:

                if i != ',':
                    # new_dict[i]=1
                    temp = int(i)
                    new_dict[temp] = 1

  
        dict = {'seats':new_dict}
        # if models.BookedSeatsModel.objects.get(movie_name='Avenger', date=date_s, time=1).exists():
        #     bookseats = models.BookedSeatsModel.objects.get(date=date_s, time=1, movie_name = movie_name) 

        # context['seats'] = new_dict
        return render(request, self.template_name, dict)

    def post(self, request, *args, **kwargs):  
        # form = self.form_class(request.POST)
        if request.method == 'POST':
            booked_seats = request.POST['booked_seats']
            print(booked_seats)
            time_s = request.session['time']
            date_s = request.session['date']    
            movie_name = request.session['moviename']
            number = request.POST['count']

            if time_s == "Manhã":
                time_fld = 1

            elif time_s == "Tarde":
                time_fld = 2
            
            elif time_s == "Noite":
                time_fld = 3

            else:
                time_fld = 4

            print(time_s)
            print(date_s)  
            
           ############Saving booked seats data################
            if models.BookedSeatsModel.objects.filter(movie_name=movie_name, date=date_s, time=time_fld).exists():
                print("same")
                obj1 = models.BookedSeatsModel.objects.get(movie_name=movie_name, date=date_s, time=time_fld)
                obj1.seats = obj1.seats + booked_seats
                obj1.number = int(obj1.number) + number
                obj1.save()

                obj = models.UserBook(user=request.user, movie_name=movie_name, date=date_s, show=time_fld, seats=booked_seats)
                obj.save()

            else:
                print("----------------------------------")
                print(request.user.id)
                print("----------------------------------")
                obj = models.UserBook(user=request.user, movie_name=movie_name, date=date_s, show=time_fld, seats=booked_seats)
                obj.save()

                obj1 = models.BookedSeatsModel(movie_name=movie_name, date=date_s, time=time_fld, seats=booked_seats, number=number)
                obj1.save()




            return redirect('../dashboard/')

        return render(request, self.template_name, dict)

class UserDashboard(generic.ListView):
    model = MovieMaster
    model_add = MovieMaster
    model_set = SetMovie
    template_name = "aplicativo_usuario/user_dashboard.html"

    def get_context_data(self, **kwargs):
        movies = MovieMaster.objects.filter(setmovie__isnull=False).distinct()
        context = super().get_context_data(**kwargs)
        context['movies'] = movies
        return context

###########Here the user will select a particular show for which he will be redirected to seat booking page############
class BuyTicket(generic.ListView):
    template_name = "aplicativo_usuario/buyticket.html"
    model = SetMovie
    from_class = forms.CheckDateForm

    def post(self, request, *args, **kwargs):

        if request.method == 'POST':
            time = request.POST['tm']
            date = request.POST['datee']

            print(time)
            print(date)
            # dict = {'time':time, 'date':date} 
            # uri = urllib.urlencode(dict)
            request.session['time'] = time
            request.session['date'] = date

            idd = self.kwargs['pk']
            movie_data = MovieMaster.objects.get(pk=idd)
            request.session['moviename'] = movie_data.m_name

            return redirect(reverse('user_side:booktickets'))

    def get_context_data(self, **kwargs):
        movies = MovieMaster.objects.filter(setmovie__isnull=False)
        context = super().get_context_data(**kwargs)
        idd = self.kwargs['pk']
        movie_data = MovieMaster.objects.get(pk=idd)
        
        context['movies'] = movie_data
        set_movie = SetMovie.objects.filter(active_id=idd)
        # print(set_movie.start_time)
        context['data_set'] = set_movie
        return context

############ User will be able to see all his/her previous bookings done #################
class BookHistory(generic.ListView):

    context_object_name = 'book_history'

    def get_queryset(self):
        return models.UserBook.objects.filter(user_id=self.request.user.id)

    template_name = "aplicativo_usuario/book_history.html"

################## User can download the ticket booked ##########################
class DownloadTicket(generic.ListView):

    context_object_name = 'ticket_detail'   
    def get_queryset(self):
        return models.UserBook.objects.filter(user_id=self.request.user.id)


    template_name = "aplicativo_usuario/downloadticket.html"

########### Single ticket download page################
class Ticket(generic.DetailView):

    context_object_name = 'row'
    def get_queryset(self):
        return models.UserBook.objects.filter(user_id=self.request.user.id)

    template_name = "aplicativo_usuario/ticket.html"
"""

aplicativo_usuario/templates/aplicativo_usuario/book_history.html
{% extends "aplicativo_usuario/baseuser.html" %}
{% load static %}


{% block head %}
<br>
<ul class="nav">
    <li><a href="{% url 'user_side:dashboard' %}" class=""><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
    <li><a href="{% url 'user_side:bookhistory' %}" class="active"><i class="lnr lnr-inbox"></i> <span>Booking History</span></a></li>

    <li><a href="{% url 'user_side:download' %}" class=""><i class="lnr lnr-download"></i> <span>Download Ticket</span></a></li>




</ul>

{% endblock %}

{% block content %}
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>

    <table>

        {% for row in book_history %}
    
            <tr>
                <td>{{row.movie_name}}</td>
                <td>{{row.date}}</td>
                <td>{{row.seats}}</td>
            </tr>
    
        {% endfor %}
    
    </table>


{% endblock %}

aplicativo_usuario/templates/aplicativo_usuario/bookticket.html
{% extends "aplicativo_usuario/baseuser.html" %}
{% load static %}

{% block head %}
<br>
<ul class="nav">
    <li><a href="{% url 'user_side:dashboard' %}" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
    <li><a href="{% url 'user_side:bookhistory' %}" class=""><i class="lnr lnr-inbox"></i> <span>Booking History</span></a></li>

    <li><a href="{% url 'user_side:download' %}" class=""><i class="lnr lnr-download"></i> <span>Download Ticket</span></a></li>

</ul>

{% endblock %}


{% block content %}

<!-- <button class="btn btn-success">testbutton</button> -->

<!-- <p id="demo" value="cc"></p> -->

<div class="container">

    <div class="container">
        
        
        <form method="POST">
            {% csrf_token %}
            <label for="form-control" style="font-weight: bold;">Seat Numbers:</label>

            <!-- <textarea disabled class="form-control" id="demo" name="booked_seats" rows="3"></textarea> -->
            <!-- <input type="textarea" disabled class="form-control" id="demo" name="booked_seats" rows="3"> -->
            <input type="text" readonly="readonly"  class="form-control" id="demo" name="booked_seats" value="">

            <label for="form-control" style="font-weight: bold;">Number of Seats:</label>
            <input type="text" readonly="readonly" class="form-control" id="count" name="count" value="">
        <br>
        <div class="jumbotron">
            {% for seat,val in seats.items %}
            
            <!-- {{val}} -->
            {% if val >= 1 %}

            <input type="image" onclick="bookSeat(this.id)" disabled = true id="{{seat}}" value="{{seat}}" src="{% static 'bk.png' %}" style="height: 80px; width: 80px;"/>

            
            {% else %}

            <input type="image" onclick="bookSeat(this.id)"  id="{{seat}}" value="{{seat}}" src="{% static 'seat.png' %}" style="height: 80px; width: 80px;"/>

            <!-- <button onclick="bookSeat(this.id)" class="btn btn-success" id="{{seat}}" value="{{seat}}" ">testbutton</button> -->
            {% endif %}
 

        {% endfor %}
        </div>
        <div class="container">


            <button class="btn btn-danger" onclick="location.reload()" style="width: 70%; position: absolute; margin-left: 120px;">Clear Booked seats</button>
            <br>
            <br>
            <!-- <button class="btn btn-success" style="width: 70%; position: absolute;margin-left: 120px;">Confirm Booking</button> -->
            <input type="submit" class="btn btn-success" style="width: 70%; position: absolute;margin-left: 120px;" value="Confirm Booking">
        </form>
            <br>
        </div>
    </div>
</div>
<br>
<br>



<script>
    function bookSeat(id)
    {

        document.getElementById('demo').value += document.getElementById(id).value+",";
        
        document.getElementById(id).src = "{% static 'booked.png' %}";
        document.getElementById(id).disabled = true;

        var val = document.getElementById("count").value;

        if(val)
        {
            val = parseInt(val)+1;
            document.getElementById("count").value = val;
        }
        else{
            document.getElementById("count").value = 1;
        }
    }
</script>


{% endblock %}

aplicativo_usuario/templates/aplicativo_usuario/buyticket.html
{% extends "aplicativo_usuario/baseuser.html" %}

{% block head %}
<br>
<ul class="nav">
    <li><a href="{% url 'user_side:dashboard' %}" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
    <li><a href="{% url 'user_side:bookhistory' %}" class=""><i class="lnr lnr-inbox"></i> <span>Booking History</span></a></li>

    <li><a href="{% url 'user_side:download' %}" class=""><i class="lnr lnr-download"></i> <span>Download Ticket</span></a></li>
   



</ul>

{% endblock %}

{% block content %}

<div class="container">
    <img src="{{movies.m_image.url}}" alt="" style="height: 400px; width: 600px; border: 5px solid #555;">
    <br>
    <h1 style="font-weight: bold; font-style: unset; font-stretch:wider;">{{movies.m_name}}</h1>
    
    <div>
            {% for data in data_set %}
        <div class="jumbotron" style="background-color:lightblue;">

                <form method="POST">

                    {% csrf_token %}
                                <label for="" style="font-weight: bold;">Start Date:</label>
                    <input type="text" readonly style="font-weight: bold;" value="{{data.start_time}}">
                    <!-- <p style="font-weight: bold;">{{data.start_time}} </p> -->

                    <br>
                    <label for="e_date" style="font-weight: bold;">End Date:</label> 
                    &nbsp;&nbsp;<input type="text" class="" readonly style="font-weight: bold;" value="{{data.end_time}} "> 
                    <!-- <p style="font-weight: bold;" id="e_date">{{data.end_time}}  </p> -->

                    <br>

                    <label for="" style="font-weight: bold;">Time:</label>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        {% if data.show == '1' %} 
                        <!-- <p style="font-weight: bold;">Morning</p>  -->
                        <input type="text" readonly style="font-weight: bold;" name="tm" value="Morning"> 
                        {% endif %}

                        {% if data.show == '2' %} 
                        <!-- <p style="font-weight: bold;">AfterNoon</p>  -->
                        <input type="text" readonly style="font-weight: bold;" name="tm" value="AfterNoon"> 
                        {% endif %}

                        {% if data.show == '3' %}
                        <!-- <p style="font-weight: bold;">Evening</p> -->
                        <input type="text" readonly style="font-weight: bold;" name="tm" value="Evening"> 
                        {% endif %}

                        {% if data.show == '4' %} 
                        <!-- <p style="font-weight: bold;">Night</p>  -->
                        <input type="text" readonly style="font-weight: bold;" name="tm" value="Night"> 
                        {% endif %}
                        <br>
                        <label for="">Cost:</label>
                        <input type="text" readonly class="form-control" style="width: 100px; font-size: large; border-width: 5px;font-weight: bold; border-color: #555;" value="{{data.price}}/-">
                    <!-- <label for="">Cost:</label> <p style="font-weight: bold;">{{data.price}}</p> -->

                        <input type="date" required class="form-control" id="" style="width:140px;" name="datee">

                        <br>
                    <input type="submit" class="btn btn-success" value="book">
                </form>
        
        </div>

    {% endfor %}
    </div>


</div>

{% endblock %}

aplicativo_usuario/templates/aplicativo_usuario/downloadticket.html
{% extends "aplicativo_usuario/baseuser.html" %}
{% load static %}
{% block head %}
<br>
<ul class="nav">
    <li><a href="{% url 'user_side:dashboard' %}" class=""><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
    <li><a href="{% url 'user_side:bookhistory' %}" class=""><i class="lnr lnr-inbox"></i> <span>Booking History</span></a></li>

    <li><a href="{% url 'user_side:download' %}" class="active"><i class="lnr lnr-download"></i> <span>Download Ticket</span></a></li>
  



</ul>



{% endblock %}


{% block content %}
<style>
    *{
        margin: 0px;
        padding: 0px;
    }
    .card{
        width: 50%;
        /* display: inline-block; */
        box-shadow: 2px 2px 20px black;
        border-radius: 5px; 
        margin: 2%;
        background-color: gainsboro;
        /* border-right: 3px dotted;
        margin-right: 50px; */
    }

    .image
    {
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        width: 100%;
    }




</style>


    {% for row in ticket_detail %}
   
<a href="{% url 'user_side:ticket' row.id %}" id="{{row.id}}"> 
    <div class="card" >
        
     
        <div class="contain">
            <div class="image" style="background-color: red;">
                <h2 style="padding: 10px; color: white; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">Cinema: {{row.user.username}}</h2>
            </div>
    
            <div class="des">
                <img src="{% static 'ticket.png' %}" style="width: 30%; height: 30%; padding-left: 9px; padding-bottom: 9px; " alt="">
                <div style="float: right; margin-right: 45%;">
                    <h2 >{{row.movie_name}}</h2>
                    <h4 >{{row.date}}</h4>
                    <h4 >Seats: {{row.seats}}</h4>
                </div>
                
            </div>
        </div>

    </div>


</a>

    {% endfor %}

    <script>
            window.onload = function(){
                document.getElementById("{{row.id}}").addEventListener("click",()=>{
                    const tic = this.document.getElementById("{{row.id}}");
                    console.log(tic);
                    console.log(window);
                    html2pdf().from(tic).save();
                })
            }
    </script>

{% endblock %}

aplicativo_usuario/templates/aplicativo_usuario/test.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>

    <div class="container-fluid">
        <div>
            <img src="" alt="../../media/pics/seat.png">
        </div>
    </div>
</html>

aplicativo_usuario/templates/aplicativo_usuario/ticket.html
{% extends "aplicativo_usuario/baseuser.html" %}
{% load static %}
{% block head %}

<style>
    *{
        margin: 0px;
        padding: 0px;
    }
    .card{
        width: 70%;
        /* display: inline-block; */
        box-shadow: 2px 2px 20px black;
        border-radius: 5px; 
        margin: 2%;
        background-color: gainsboro;
        /* border-right: 3px dotted;
        margin-right: 50px; */
    }

    .image
    {
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        width: 100%;
    }




</style>
<script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js' %}"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.min.js"></script>
<br>
<ul class="nav">
    <li><a href="{% url 'user_side:dashboard' %}" class=""><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
    <li><a href="{% url 'user_side:bookhistory' %}" class=""><i class="lnr lnr-inbox"></i> <span>Booking History</span></a></li>

    <li><a href="{% url 'user_side:download' %}" class="active"><i class="lnr lnr-download"></i> <span>Download Ticket</span></a></li>
  



</ul>



{% endblock %}



{% block content %}

<div class="card" id="content">
        
     
    <div class="image" style="background-color: red;">
        <h2 style="padding: 10px; color: white; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">Cinema: {{row.user.username}}</h2>
    </div>

    <div class="des">
        <img src="{% static 'ticket.png' %}" style="width: 30%; height: 30%; padding-left: 9px; padding-bottom: 9px; " alt="">
        <div style="float: right; margin-right: 45%;">
            <h2 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">{{row.movie_name}}</h2>
            <h4 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">{{row.date}}</h4>
            <h4 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Seats: {{row.seats}}</h4>
        </div>


        
    </div>

</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button class="btn btn-success" id="download">Downlaod</button>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
<script>
window.onload = function () {
    document.getElementById("download")
        .addEventListener("click", () => {
            const invoice = this.document.getElementById("content");
            console.log(invoice);
            console.log(window);
            var opt = {
                margin: 1,
                filename: 'myfile.pdf',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
            };
            html2pdf().from(invoice).set(opt).save();
        })
}
</script>

{% endblock %}

aplicativo_usuario/templates/aplicativo_usuario/user_dashboard.html
{% extends "aplicativo_usuario/baseuser.html" %}

{% block head %}
<br>
<ul class="nav">
    <li><a href="{% url 'user_side:dashboard' %}" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
    <li><a href="{% url 'user_side:bookhistory' %}" class=""><i class="lnr lnr-inbox"></i> <span>Booking History</span></a></li>

    <li><a href="{% url 'user_side:download' %}" class=""><i class="lnr lnr-download"></i> <span>Download Ticket</span></a></li>
    <!-- <li><a href="notifications.html" class=""><i class="lnr lnr-user"></i> <span>Users</span></a></li> -->



</ul>
    
{% endblock %}

{% block content %}
<style>

</style>
{% for movie in movies %}

        <a href="{% url 'user_side:selectseats' movie.pk %}"><img src="{{movie.m_image.url}}" alt="" style="height: 350px; width: 270px; border: 5px solid #555;"></a>&nbsp;&nbsp;&nbsp



{% endfor %}

{% endblock %}