GerenciaCinema/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from aplicativo.urls import urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urlpatterns))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicativo/urls.py
from django.conf.urls.static import static
from aplicativo.views import index, index_auth, filmes, sessoes, assentos, logar, deslogar, cadastro, administrador, indisponivel
from django.urls import path
from GerenciaCinema import settings

app_name = 'aplicativo'

urlpatterns = [
    path('', index),
    path('indisponivel', indisponivel, name='indisponivel'),
    path('index_auth', index_auth, name='index_auth'),
    path('filmes', filmes, name='filmes'),
    path('sessoes', sessoes, name='sessoes'),
    path('assentos', assentos, name='assentos'),
    path('logar', logar, name='logar'),
    path('deslogar', deslogar, name='deslogar'),
    path('cadastro', cadastro, name='cadastro'),
    path('administrador', administrador, name='administrador'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicativo_usuario/urls.py
"""from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='user_side'

urlpatterns = [
    path('dashboard/', views.UserDashboard.as_view(), name='dashboard'),
    path('booktickets/', views.BookTickets.as_view(), name='booktickets'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('selectseats/<int:pk>', views.BuyTicket.as_view(), name='selectseats'),
    path('history/', views.BookHistory.as_view(), name='bookhistory'),
    path('download/', views.DownloadTicket.as_view(), name='download'),
    path('ticket/<int:pk>', views.Ticket.as_view(), name ='ticket')
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

aplicativo/models.py
from django.db import models
from stdimage import StdImageField

class Filme(models.Model):
    CLASSIFICACAO_CHOICES = (
        ('Livre', 'Livre'), ('10+', '10+'), ('12+', '12+'), ('14+', '14+'),
        ('16+', '16+'), ('18+', '18+')
    )

    nome = models.CharField('Nome', max_length=32)
    sinopse = models.CharField('Sinopse', max_length=500)
    classificacao = models.CharField(max_length=32, choices=CLASSIFICACAO_CHOICES)
    duracao = models.CharField('Duração', max_length=16)
    capa = StdImageField('Capa do Filme', upload_to='imagens', variations={'thumb': (90, 90)})
    trailer = models.URLField("Trailer do Filme", max_length=100)

    def __str__(self):
        return "{}".format(self.nome)

class Sessao(models.Model):
    dataCartaz = models.DateTimeField(verbose_name='Data do Cartaz')
    filme = models.ForeignKey(Filme, on_delete=models.CASCADE)

    def __str__(self):
        return "Sessão de {}, dia {} ás {}".format(self.filme.nome, self.dataCartaz.strftime('%d/%m/%Y'), self.dataCartaz.strftime('%H:%M'))
    
class Assentos(models.Model):
    ocupado = models.BooleanField(default=False)
    sessao = models.ForeignKey(Sessao, on_delete=models.CASCADE)
    
    def __str__(self):
        if self.livre == True:
            return "{} | Livre".format(self.sessao.dataCartaz)
        else:
            return "{} | Ocupado".format(self.sessao.dataCartaz)

aplicativo/forms.py
from django import forms
from GerenciaCinema import settings
from aplicativo.models import Filme, Sessao, Assentos

class FilmesModelForm(forms.ModelForm):
    class Meta:
        model = Filme
        fields = ['nome', 'sinopse', 'classificacao', 'duracao', 'capa', 'trailer']
        widgets = {
            'duracao': forms.TextInput(attrs={'placeholder': '0h00m'})
        }

class SessaoModelForm(forms.ModelForm):
    class Meta:
        model = Sessao
        fields = ['filme', 'dataCartaz']
        widgets = {
            'dataCartaz': forms.DateInput(format=settings.DATETIME_INPUT_FORMATS,
                                          attrs={'placeholder': 'Ex: 01/01/2000 00:00'})
        }

class AssentoModelForm(forms.ModelForm):
    class Meta:
        model = Assentos
        fields = ['ocupado', 'sessao']
        widgets = {
            'ocupado': forms.HiddenInput(),
        }

aplicativo/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from aplicativo.models import Filme, Assentos
from aplicativo.forms import FilmesModelForm, SessaoModelForm, AssentoModelForm
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
# Create your views here.

def index(request):
    context = {
    'filmes': Filme.objects.all()
    }
    return render(request, 'index.html', context)

def indisponivel(request):
    return render(request, 'indisponivel.html')

def index_auth(request):
    context = {
    'filmes': Filme.objects.all()
    }
    if request.user.is_authenticated:
        return render(request, 'index_auth.html', context)
    else:
        return redirect(logar)
    
def administrador(request):
    if request.user.is_superuser:
        return render(request, 'administrador.html')
    else:
        return redirect(index_auth)

def logar(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, 'Usuário conectado!')
            return redirect(index_auth)
    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }
    return render(request, 'logar.html', context)

def deslogar(request):
    if request.method == 'POST':
        logout(request)
        return redirect(index_auth)

def cadastro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():

            form.save()
            messages.success(request, 'Usuário cadastrado!')
            form = UserCreationForm()
        else:
            messages.error(request, 'Usuário não cadastrado!')
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }
    return render(request, 'cadastro.html', context)

def filmes(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = FilmesModelForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, 'Filme adicionado com sucesso!')
                form = FilmesModelForm()
            else:
                messages.error(request, 'Erro! Filme não pôde ser adicionado.!')
        else:
            form = FilmesModelForm()
        context = {
            'form': form
        }
        return render(request, 'filmes.html', context)
    else:
        return redirect(index_auth)

def sessoes(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = SessaoModelForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Sessão criada com sucesso.')
                form = SessaoModelForm()
            else:
                messages.error(request, 'Erro! Sessão não pôde ser criada.')
        else:
            form = SessaoModelForm()
        context = {
            'form': form
        }
        return render(request, 'sessoes.html', context)
    else:
        return redirect(index_auth)

def assentos(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = AssentoModelForm(request.POST)
            if form.is_valid():
                messages.success(request, 'Assento adicionado!')
            else:
                messages.error(request, 'Erro! Assento não pôde ser adicionado.')
        else:
            form = AssentoModelForm()
        context = {
            'form': form,
            'assento': Assentos.objects.all()
        }
        return render(request, 'assentos.html', context)
    else:
        return redirect(index_auth)

aplicativo/templates/aplicativo/addmovies.html
{% extends "movie/admin_base.html" %}

{% block content %}


<div class="form-group">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class="btn btn-success" value="submit">
    
    </form>

</div>


{% endblock %}

aplicativo/templates/aplicativo/admin_base.html
{% load static %}

<!doctype html>
<html lang="pt-br">

<head>
	<title>Dashboard | Klorofil - Free Bootstrap Dashboard Template</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

    <link rel="stylesheet" href="{% static 'date/css/pikaday.css' %}">
    <link rel="stylesheet" href="{% static 'date/css/site.css' %}">

	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/chartist/css/chartist-custom.css' %}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="{% static 'assets/css/demo.css' %}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
</head>

<body>
	<div id="wrapper">
		<!-- Barra de navegação -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<!-- comentario -mudar a imagem ou tirar
			<div class="brand">
				<a href="index.html"><img src="{% static 'assets/img/logo-dark.png' %}" alt="Logo" class="img-responsive logo"></a>
			</div>
			-->
			<div class="container-fluid">
				<div class="navbar-btn">
					<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
				</div>

				<form class="navbar-form navbar-left">
					<!-- comentario - tirei o placeholder="Pesquisar...", depois colocar de volta e add um botão com simbolo de lupa ou apagar esse comentario-->
					<div class="input-group">
						<input type="text" value="" class="form-control">
						<span class="input-group-btn"><button type="button" class="btn btn-primary">Pesquisar</button></span>
					</div>
				</form>
		
				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">

						<li class="dropdown">
							<!-- comentario - mudar a imagem ou tirar -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'assets/img/user.png' %}" class="img-circle" alt="Avatar"> <span>{{request.user.username}}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<!--
								<li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
								<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
								<li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
								-->
								<li><a href="{% url 'user_side:logout' %}"><i class="lnr lnr-exit"></i> <span>Sair</span></a></li>
							</ul>
						</li>
						<!-- <li>
							<a class="update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
						</li> -->
					</ul>
				</div>
			</div>
		</nav>
		<!-- menu lateral -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<li><a href="{% url 'setadmin:dashboard' %}" class="active"><i class="lnr lnr-home"></i> <span>Painel</span></a></li>
						<li><a href="{% url 'setadmin:addmovie' %}" class=""><i class="lnr lnr-text-format"></i> <span>Adicionar filmes</span></a></li>

						<li><a href="{% url 'setadmin:setmovie' %}" class=""><i class="lnr lnr-cog"></i> <span>Liberar filmes</span></a></li>
						<li><a href="notifications.html" class=""><i class="lnr lnr-user"></i> <span>Usuários</span></a></li>
					</ul>
				</nav>
			</div>
		</div>

		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
				<div class="container-fluid">
					<br>
					<!-- OVERVIEW -->

					<!-- END OVERVIEW -->
					<!-- ---------------------------------------------------------------------------------- -->
					{% block content %}


					{% endblock %}
					<!-- ------------------------------------------------ -->
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<div class="text-center">
					<a href="https://github.com/Bezerha/Cine_Familia"> Version 2.0.1 </a> &copy; 2022 CineFamilia
				</div>
			</div>
		</footer>
	</div>
	<!-- Javascripts - mudar depois -->
	<script src="{% static 'date/moment.js' %}"></script>
	<script src="{% static 'date/pikaday.js' %}"></script>

	<script>
		var picker = new Pikaday({
			field: document.getElementById('datepicker'),
			format: 'YYYY-MM-DD',
			onSelect: function() {
				console.log(this.getMoment().format('YYYY-MM-DD'));
			}
		});
	</script>

	<script>
		var picker = new Pikaday({
			field: document.getElementById('datepicker1'),
			format: 'YYYY-MM-DD',
			onSelect: function () {
				console.log(this.getMoment().format('YYYY-MM-DD'));
				theme: 'dark-theme'
			}
		});
	</script>

	<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static 'assets/vendor/chartist/js/chartist.min.js' %}"></script>
	<script src="{% static 'assets/scripts/klorofil-common.js' %}"></script>

	<script>
	$(function() {
		var data, options;

		// headline charts
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[23, 29, 24, 40, 25, 24, 35],
				[14, 25, 18, 34, 29, 38, 44],
			]
		};

		options = {
			height: 300,
			showArea: true,
			showLine: false,
			showPoint: false,
			fullWidth: true,
			axisX: {
				showGrid: false
			},
			lineSmooth: false,
		};

		new Chartist.Line('#headline-chart', data, options);


		// visits trend charts
		data = {
			labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			series: [{
				name: 'series-real',
				data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
			}, {
				name: 'series-projection',
				data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
			}]
		};

		options = {
			fullWidth: true,
			lineSmooth: false,
			height: "270px",
			low: 0,
			high: 'auto',
			series: {
				'series-projection': {
					showArea: true,
					showPoint: false,
					showLine: false
				},
			},
			axisX: {
				showGrid: false,

			},
			axisY: {
				showGrid: false,
				onlyInteger: true,
				offset: 0,
			},
			chartPadding: {
				left: 20,
				right: 20
			}
		};

		new Chartist.Line('#visits-trends-chart', data, options);


		// visits chart
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[6384, 6342, 5437, 2764, 3958, 5068, 7654]
			]
		};

		options = {
			height: 300,
			axisX: {
				showGrid: false
			},
		};

		new Chartist.Bar('#visits-chart', data, options);


		// real-time pie chart
		var sysLoad = $('#system-load').easyPieChart({
			size: 130,
			barColor: function(percent) {
				return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
			},
			trackColor: 'rgba(245, 245, 245, 0.8)',
			scaleColor: false,
			lineWidth: 5,
			lineCap: "square",
			animate: 800
		});

		var updateInterval = 3000; // in milliseconds

		setInterval(function() {
			var randomVal;
			randomVal = getRandomInt(0, 100);

			sysLoad.data('easyPieChart').update(randomVal);
			sysLoad.find('.percent').text(randomVal);
		}, updateInterval);

		function getRandomInt(min, max) {
			return Math.floor(Math.random() * (max - min + 1)) + min;
		}

	});
	</script>
</body>

</html>

aplicativo/templates/aplicativo/admin_login.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>

    <body style="background-color:700fb0">
        <br><br><br>

        <!-- mudar a cor desse container -->
        <div class="container">
            <div class="container">
                <div class="container">
                    
                    <div class="jumbotron" style="width: 40%; margin-left: 32%; background-color:16c79a">
                        <!--  comentario -  mudar para uma imagem ao inves do nome "Acesso do usuário" ????
                         <img src="{% static 'logo.jpg'%}" style="height: 80px; width: 80px;" alt=""> -->
                        <h2 style="color: aliceblue; font-style:oblique; margin-left: 26%;">Acesso do usuário</h2>
                        <br>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                              <label for="exampleInputEmail1">Usuário:</label>
                              <input type="text" class="form-control" id="exampleInputEmail1" name="username"  placeholder="Nome de usuário">
                             </small>
                            </div>
                            <div class="form-group">
                              <label for="exampleInputPassword1">Senha:</label>
                              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Senha">
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary" style="width: 100%;">Entrar</button>
                          </form>
                          <a href="{% url 'user_side:login' %}" style="margin-left: 42%;">Entrar como usuário</a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

aplicativo/templates/aplicativo/chart.html
{% extends "movie/admin_base.html" %}
{% load static %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<script>

    $(function () {

      var $populationChart = $("#population-chart");
      $.ajax({
        url: $populationChart.data("url"),
        success: function (data) {

          var ctx = $populationChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Population',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Population Bar Chart'
              }
            }
          });

        }
      });

    });

  </script>

{% endblock %}

aplicativo/templates/aplicativo/dashboard.html
{% extends "movie/admin_base.html" %}

{% block content %}

{% for movie in movies %}


<img src="{{movie.m_image.url}}" alt="" style="height: 350px; width: 250px; border: 5px solid #555;">


{% endfor %}

{% endblock %}

aplicativo/templates/aplicativo/setmovies.html
{% extends "movie/admin_base.html" %}
{% load static %}
{% block content %}


<div class="form-group">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class="btn btn-success" value="submit">
    
    </form>

</div>


{% endblock %}